---
- include_tasks: dev.yml
  when: _apb_plan_id == "dev"

- include_tasks: prod.yml
  when: _apb_plan_id == "prod"

- name: set {{ service_name }} service state to {{ state }}
  k8s_v1_service:
    name: "{{ service_name }}"
    namespace: '{{ namespace }}'
    state: "{{ state }}"
    labels:
      app: rhscl-mariadb-apb
      service: "{{ service_name }}"
    selector:
      app: rhscl-mariadb-apb
      service: "{{ service_name }}"
    ports:
    - name: port-3306
      port: 3306
      protocol: TCP
      target_port: 3306
  register: mariadb_service

- name: encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: "mysql"
      DB_HOST: "{{ service_name }}"
      DB_PORT: "3306"
      DB_USER: "{{ mysql_user }}"
      DB_PASSWORD: "{{ mysql_password }}"
      DB_NAME: "{{ mysql_database }}"
  when: state == "present"
