---
- block:
  - name: Find pod we need to update
    shell: oc get pods -n {{ namespace }} -l app=rhscl-mariadb-apb -o custom-columns=name:.metadata.name --no-headers
    register: oldpod

  - name: Find dc we will clean up
    shell: oc get dc -n {{ namespace }} -l app=rhscl-mariadb-apb -o custom-columns=name:.metadata.name --no-headers
    register: olddc

  - name: Backup source database
    shell:  oc exec -n {{ namespace }} {{ oldpod.stdout }} -- /bin/bash -c "mysqldump -u root --all-databases > /tmp/db.dump"

  - name: Copy over db backup
    shell: oc cp -n {{ namespace }} {{ oldpod.stdout }}:/tmp/db.dump /tmp/db.dump
  when: update is defined

- name: set {{ service_name }} service state to {{ state }}
  k8s_v1_service:
    name: "{{ service_name }}"
    namespace: '{{ namespace }}'
    state: "{{ state }}"
    labels:
      app: rhscl-mariadb-apb
      service: "{{ service_name }}"
    selector:
      app: rhscl-mariadb-apb
      service: "{{ service_name }}-{{ mariadb_version }}-{{ _apb_plan_id }}"
    ports:
    - name: port-3306
      port: 3306
      protocol: TCP
      target_port: 3306
  register: mariadb_service

- include_tasks: dev.yml
  when: _apb_plan_id == "dev"

- include_tasks: prod.yml
  when: _apb_plan_id == "prod"

- block:
  - name: Wait for mariadb to come up
    wait_for:
      port: 3306
      host: "{{ mariadb_service.service.spec.cluster_ip }}"
      timeout: 300

  - name: Find pod we need to restore
    shell: oc get pods -n {{ namespace }} --show-all=false -l service={{ service_name }}-{{ mariadb_version }}-{{ _apb_plan_id }} -o custom-columns=name:.metadata.name --no-headers
    register: newpod

  - block:
    - name: Copy over db backup
      shell: oc cp -n {{ namespace }} /tmp/db.dump {{ newpod.stdout }}:tmp/db.dump

    - name: Restore database
      shell:  oc exec -n {{ namespace }} {{ newpod.stdout }} -- /bin/bash -c "mysql -u root  < /tmp/db.dump"

    - name: Remove old dc
      openshift_v1_deployment_config:
        name: "{{ olddc.stdout }}"
        namespace: '{{ namespace }}'
        state: absent

    - name: ensure production volume is absent
      k8s_v1_persistent_volume_claim:
        name: "{{ service_name }}-{{ item }}-prod"
        namespace: '{{ namespace }}'
        access_modes:
          - ReadWriteOnce
        resources_requests:
          storage: '{{ volume_size }}'
        state: "absent"
      with_items:
        - "10.0"
        - "10.1"
        - "10.2"
      when: _apb_plan_id == "dev" or item != mariadb_version
    when: newpod.stdout != oldpod.stdout
  when: update is defined

- name: encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: "mysql"
      DB_HOST: "{{ service_name }}"
      DB_PORT: "3306"
      DB_USER: "{{ mariadb_user }}"
      DB_PASSWORD: "{{ mariadb_password }}"
      DB_NAME: "{{ mariadb_database }}"
  when: state == "present"
