---

apiVersion: {{ pvc_api_version }}
kind: PersistentVolumeClaim
metadata:
  name: {{ app_name }}
  namespace: {{ namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ mariadb_volume_size }}
