- name: Deploy rhscl-mariadb-apb to openshift
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: rhscl-mariadb-apb-openshift
    playbook_debug: false
